services:
  winbox:
    image: frici/winbox
    container_name: winbox
    restart: on-failure
    network_mode: host
    environment:
      - DISPLAY=:0
      - ipc=host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - winboxdata:/winbox/
